language: java
dist: trusty
branches:
  only:
    - master
jdk:
  - oraclejdk8
services:
  - postgresql
before_script:
  - psql -c "CREATE DATABASE orientdb;" -U postgres
  - psql -c "CREATE USER orientuser WITH PASSWORD 'orientpassword';" -U postgres

deploy:
  provider: heroku
  api-key:
    secure: $HEROKU_API_KEY
  app: orientmsk

addons:
  sonarcloud:
    organization: "nvivanov-github"
    token:
      secure: $SONAR_TOKEN
    branches:
      - master
script:
  - sonar-scanner